class MedicineData {
  static const Map<String, List<String>> medicineCategories = {
    // 'A': [
    //   // ACEi
    //   'Captopril',
    //   'Enalapril',
    //   'Ramipril',
    //   'Benazepril',
    //   'Lisinopril',
    //   'Perindopril',
    //   'Quinapril',
    //   'Trandolapril',
    //   // ARBs
    //   'Losartan',
    //   'Telmisartan',
    //   'Valsartan',
    //   'Olmesartan',
    //   'Irbesartan',
    //   'Azilsartan',
    //   'Candesartan',
    //   // ARNIs
    //   'Sacubitril-valsartan',
    //   // Isolazine
    //   'Hydralazine and Isosorbide dinitrate',
    // ],
    // 'B': [
    //   // Beta-blockers
    //   'Acebutolol',
    //   'Atenolol',
    //   'Bisoprolol',
    //   'Carvedilol',
    //   'Labetalol',
    //   'Metoprolol',
    //   'Nadolol',
    //   'Pindolol',
    //   'Propranolol',
    //   'Timolol',
    //   'Ivabradine',
    // ],
    // 'C': [
    //   // SGLT-2i
    //   'Dapagliflozin',
    //   'Empagliflozin',
    //   'Sotagliflozin',
    //   'Digoxin',
    //   'Vericiguat',
    //   // Blood thinners
    //   'Warfarin',
    //   'Dabigatran',
    //   'Rivaroxaban',
    //   // STATINs
    //   'Atorvastatin',
    //   'Fluvastatin',
    //   'Lovastatin',
    //   'Pitavastatin',
    //   'Pravastatin',
    //   'Rosuvastatin',
    //   'Simvastatin',
    //   // Fibrates
    //   'Fenofibrate',
    //   'Clofibrates',
    //   // Bile acid sequestrants
    //   'Cholestyramine',
    //   'Colesevelam',
    //   'Colestipol',
    //   // Others
    //   'Ezetimibe',
    //   'Bempedoic acid',
    //   'Niacin',
    //   'Omega-3 fatty acids',
    // ],
    // 'D': [
    //   // Diuretics
    //   'Hydrochlorothiazide',
    //   'Bumetanide',
    //   'Metolazone',
    //   'Chlorthalidone',
    //   'Furosemide',
    //   'Indapamide',
    //   'Etacrynic acid',
    //   'Triamterene',
    //   'Amiloride',
    //   'Spironolactone',
    // ],
    'A': [
      'Azilsartan',
      'Benazepril',
      'Candesartan',
      'Captopril',
      'Enalapril',
      'Hydralazine and Isosorbide dinitrate',
      'Irbesartan',
      'Lisinopril',
      'Losartan',
      'Olmesartan',
      'Perindopril',
      'Quinapril',
      'Ramipril',
      'Sacubitril-valsartan',
      'Telmisartan',
      'Valsartan'
    ],
    'B': [
      'Acebutolol',
      'Atenolol',
      'Bisoprolol',
      'Carvedilol',
      'Ivabradine',
      'Labetalol',
      'Metoprolol',
      'Nadolol',
      'Pindolol',
      'Propranolol',
      'Timolol'
    ],
    'C': [
      'Atorvastatin',
      'Bempedoic acid',
      'Cholestyramine',
      'Clofibrates',
      'Colesevelam',
      'Colestipol',
      'Dabigatran',
      'Dapagliflozin',
      'Digoxin',
      'Empagliflozin',
      'Ezetimibe',
      'Fenofibrate',
      'Fluvastatin',
      'Lovastatin',
      'Niacin',
      'Omega-3 fatty acids',
      'Pitavastatin',
      'Pravastatin',
      'Rivaroxaban',
      'Rosuvastatin',
      'Simvastatin',
      'Sotagliflozin',
      'Vericiguat',
      'Warfarin'
    ],
    'D': [
      'Amiloride',
      'Bumetanide',
      'Chlorthalidone',
      'Etacrynic acid',
      'Furosemide',
      'Hydrochlorothiazide',
      'Indapamide',
      'Metolazone',
      'Spironolactone',
      'Triamterene'
    ]
  };
}